[FLINK-30232][Build/Shaded] Include all platforms incl ARM64 while shading Netty
apache/flink-shaded pull request #118
Opened 2022-12-21 11:01 UTC by MartijnVisser

2023-01-13 15:52 UTC, zentol commented on flink-shaded-netty-4/pom.xml
> +                                    <mapper type="glob" from="libnetty_transport_native_kqueue_*.jnilib" to="liborg_apache_flink_shaded_netty4_netty_transport_native_kqueue_*.jnilib"/>
if these patterns actually work we could merge the epoll/kqueue moves and significantly streamline things.

```
from:  libnetty*
to:    liborg_apache_flink_shaded_netty*
```

2023-01-13 15:53 UTC, zentol commented on flink-shaded-netty-4/pom.xml
> +                                    <mapper type="glob" from="libnetty_transport_native_kqueue_*.jnilib" to="liborg_apache_flink_shaded_netty4_netty_transport_native_kqueue_*.jnilib"/>
Not sure if there is other stuff in the native directory that we wouldnt want relocated.

2023-01-17 13:06 UTC, zentol requested changes
This doesn't cover all native files of netty4. There are some macos-specific resolved libraries that also need to be relocated.
If you follow my suggestion these should be automatically covered.

The same streamlining should be applied to the dynamic tcnative module, whereas the static tcnative module is also missing a relocation for macos.

2023-01-18 10:26 UTC, MartijnVisser commented
> The same streamlining should be applied to the dynamic tcnative module

We can't do that for the dynamic tcnative module, per https://github.com/apache/flink-shaded/blob/master/flink-shaded-netty-tcnative-dynamic/pom.xml#L157 - I've tried to streamline it but then it doesn't work properly. The other comments have been taken care off

2023-01-18 11:41 UTC, zentol approved these changes

2023-01-19 09:12 UTC, merged